export interface Movie{
    poster_path: string,
    adult: boolean,
    overview: string,
    release_date: string,
    genre_ids: Array<number>,
    id: number,
    original_name: string,
    original_title: string,
    original_language: string,
    title: string,
    backdrop_path: string,
    popularity: number,
    vote_count: number,
    video: boolean,
    vote_average: number,
    first_air_date: string,
    production_companies: Array<any>,
    genres: Array<any>,
    tagline: string,
    status: string,
    runtime: number,
}